const { Product } = require("../models");

const productData = [
  {
    productName: "Plain T-Shirt",
    price: 14.99,
    stock: 14,
    categoryId: 1,
  },
  {
    productName: "Red Boucle Shirt",
    price: 16.99,
    stock: 24,
    categoryId: 1,
  },
  {
    productName: "White Pearl T-Shirt",
    price: 2.99,
    stock: 18,
    categoryId: 1,
  },
  {
    productName: "Blue Satin Solid Shirt",
    price: 7.99,
    stock: 11,
    categoryId: 1,
  },
  {
    productName: "Green Stronghold Print T-Shirt",
    price: 8.99,
    stock: 12,
    categoryId: 1,
  },
  {
    productName: "Running Sneakers",
    price: 90.0,
    stock: 25,
    categoryId: 5,
  },
  {
    productName: "Blue Studded Ballerina Shoes",
    price: 9.0,
    stock: 28,
    categoryId: 5,
  },
  {
    productName: "Stacey Solomon Older Girl White Chunky Trainers",
    price: 25.0,
    stock: 22,
    categoryId: 5,
  },
  {
    productName: "White Penn Cup Sole Trainers",
    price: 20.0,
    stock: 15,
    categoryId: 5,
  },
  {
    productName: "Red Chelsea Boots",
    price: 30.0,
    stock: 35,
    categoryId: 5,
  },
  {
    productName: "Branded Baseball Hat",
    price: 22.99,
    stock: 12,
    categoryId: 4,
  },
  {
    productName: "Holographic Shower Cap",
    price: 0.99,
    stock: 12,
    categoryId: 4,
  },
  {
    productName: "Beige Borg Baseball Cap",
    price: 3.99,
    stock: 18,
    categoryId: 4,
  },
  {
    productName: "Red Herringbone Pattern Flat Cap",
    price: 5.99,
    stock: 16,
    categoryId: 4,
  },
  {
    productName: "Christmas Gifting Green The Grinch Shower Cap",
    price: 2.99,
    stock: 28,
    categoryId: 4,
  },
  {
    productName: "Top 40 Music Compilation Vinyl Record",
    price: 12.99,
    stock: 50,
    categoryId: 3,
  },
  {
    productName: "Dolly Parton, Songteller: My Life in Lyrics",
    price: 37.99,
    stock: 25,
    categoryId: 3,
  },
  {
    productName: "Orba Handheld Multi-Instrument",
    price: 94.99,
    stock: 15,
    categoryId: 3,
  },
  {
    productName: "Wall Guitar Hanger",
    price: 250.99,
    stock: 10,
    categoryId: 3,
  },
  {
    productName: "Cannonball Gourd Thumb Piano",
    price: 38.99,
    stock: 45,
    categoryId: 3,
  },
  {
    productName: "Cargo Shorts",
    price: 29.99,
    stock: 22,
    categoryId: 2,
  },
  {
    productName: "Charcoal Modal Pyjama Shorts",
    price: 5.99,
    stock: 42,
    categoryId: 2,
  },
  {
    productName: "Camouflage Utility Cargo Shorts",
    price: 14.99,
    stock: 28,
    categoryId: 2,
  },
  {
    productName: "Red Relaxed Belted Shorts",
    price: 10.99,
    stock: 8,
    categoryId: 2,
  },
  {
    productName: "Blue Cable Knit Shorts",
    price: 9.99,
    stock: 21,
    categoryId: 2,
  },
  {
    productName: "Golden Satin Mesh Premium Lingerie Set",
    price: 7.0,
    stock: 14,
    categoryId: 6,
  },
  {
    productName: "Ivory Brazilian Briefs",
    price: 5.0,
    stock: 10,
    categoryId: 6,
  },
  {
    productName: "Premium Mocha Satin Bralette",
    price: 10.99,
    stock: 25,
    categoryId: 6,
  },
  {
    productName: "Blue Maximise Underwired Bra",
    price: 12.99,
    stock: 8,
    categoryId: 6,
  },
  {
    productName: "White Plain Acrylic Sweater",
    price: 4.99,
    stock: 14,
    categoryId: 7,
  },
  {
    productName: "Red Positive Print Sweater",
    price: 8.99,
    stock: 24,
    categoryId: 7,
  },
  {
    productName: "White Turtle Neck Sweater",
    price: 25.99,
    stock: 8,
    categoryId: 7,
  },
  {
    productName: "Golden Moss Stitch Twist Sweater",
    price: 54.99,
    stock: 44,
    categoryId: 7,
  },
  {
    productName: "Green Moss Stitch Twist Sweater",
    price: 14.99,
    stock: 9,
    categoryId: 7,
  },
  {
    productName: "Red Positive Print Sweater",
    price: 19.99,
    stock: 11,
    categoryId: 7,
  },
  {
    productName: "Younger Girl Green Disney Princess Sweater",
    price: 4.99,
    stock: 24,
    categoryId: 7,
  },
  {
    productName: "Ivory Print Winnie The Pooh Cares Sweater",
    price: 20.99,
    stock: 16,
    categoryId: 7,
  },
];

const seedProducts = () => Product.bulkCreate(productData);

module.exports = seedProducts;
